### ISSUE TITLE
Twenty Twenty One Styles

### ISSUE THREAD

**Issue by helgatheviking** [helgatheviking/wc-mnm-checkboxes#7]
Twenty Twenty One has some fancy checkbox styles

![image](https://user-images.githubusercontent.com/507025/113343937-b36b7300-92ed-11eb-84ca-49a410996ba1.png)

which don't seem to be applied to ours:
![image](https://user-images.githubusercontent.com/507025/113343873-9afb5880-92ed-11eb-835f-4ac8f235712b.png)

**Comment by ednorripplepop** [comment]
I just pull requests on 2.0-dev for fixing the checkbox issue on mini-extension plugin
